### ISSUE TITLE
 'cache API not available' and 'cache put failed' warnings

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-common-component#21]
'cache API not available' and 'cache put failed' have always been sent to BQ, but their occurrence is ever increasing and count up to more than 15% of the number of displays running rise-data-weather. ( rise-data-rss is now also logging 'cache put failed' ).

We should investigate what may be wrong with the displays that are failing, and if there's a way to avoid having such a high failure rate on caching ( maybe use localStorage as a fall-back ? ).

**Comment by alex-deaconu** [comment]
@santiagonoguez this issue was resolved by using `localStorage` as a backup to the `cache` API for http.

Regarding logging, we are still going to log the `cache API not available` warning despite the fallback, for debugging purposes, but improve our code to only log it once per day (along with other cache related logs).

To confirm, we are also facing another issue with Electron players re: `cache.put` which is unrelated, and is being fixed separately.

Thanks.

**Comment by santiagonoguez** [comment]
@alex-deaconu sounds good, thanks !
